server:
  port: 9200 #指定服务端口

spring:
  application:
    name: eureka-server


eureka:
  instance:
    hostname: eureka-server-1 #设置当前实例的主机名称
  server:
      enable-self-preservation: false #关闭自我保护机制
  client:
    registerWithEureka: false #是否将eureka自身作为应用注册到eureka注册中心，false表示当前服务不需要到eureka服务上注册，自身就是服务（单机），true表示将自己注册（集群），默认true
    fetchRegistry: false #是否需要拉取注册实例信息