server:
  port: 9100 #指定服务端口
  servlet:
      context-path: /orderProviderContext #项目上下文

spring:
  application:
    name: order-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/ #eureka-server部署的地址（把自己注册到哪）